# Generated by Django 5.1.6 on 2025-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الرحلة')),
                ('location', models.CharField(default='Default Location', max_length=200, verbose_name='موقع الرحلة')),
                ('responsible_phone', models.CharField(max_length=20, verbose_name='هاتف المسؤول')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration', models.CharField(max_length=50, verbose_name='المدة')),
                ('capacity', models.PositiveIntegerField(verbose_name='السعة')),
                ('image', models.ImageField(upload_to='trips/', verbose_name='الصورة')),
                ('date', models.DateTimeField(verbose_name='تاريخ الرحلة')),
            ],
        ),
    ]
